### ISSUE TITLE
revision needed for the question flow

### ISSUE THREAD

**Issue by MonicaLLLMMM** [iris-shanghai/ihg.survey#2]
hi mike,

几个问题需要修改：
1. 问题2 选了答案以后，跳出弹框，弹框中需要显示问题内容。用户点“继续”后，不再出现问题3，直接显示问题4.但是问题4我们写成“问题3”。
2. 现在没有error page，需要设定用户不回答完全部的问题无法提交。error page的copy参考我昨天给的word文档。
3. 回答完以后的“thank you page", 文案参考我昨天给的word文档。
4. tnc的内容马上发你。

以上，谢谢。

monica

**Comment by MonicaLLLMMM** [comment]
hi mike,

几个点先修改下：
1. 弹出的tnc 内容我qq给你
2. tnc以后直接开始回答问题，填信息的放到最后填好信息后出现
3. 问卷没有填完就提交的，要有页面提示（如下）

请将问卷填写完整，让IHG更懂你。
1. 最后一页 thank you page 文字：

感谢你参与IHG® 优悦会问卷调研！

现在就关注“IHG优悦会”微信号，第一时间了解最新优惠信息，让IHG与你更亲近。

以上，谢谢。

monica

**Comment by iamike** [comment]
fixed
